name: Generate Snake Animation

on:
  schedule:
    # Executa todos os dias às 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.GuilhermeCamargoL }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Atualiza snake.svg e variantes"
          add: "dist/"
